version: '3'

services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    # links:
    #   - mongo:mongo
    depends_on:
      - mongo
    environment:
      - ADMIN_USERNAME=USERADMIN
      - PORT=8888
      - MONGODB_DOMAIN=ognom:adminispw@mongo:27017
    working_dir: /opt/app
    # command: [ls]
    restart: unless-stopped
    volumes:
      - /opt/app/node_modules
      - ./app:/opt/app/app
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      # - ./tsconfig.json:/opt/app/tsconfig.json

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ognom
      - MONGO_INITDB_ROOT_PASSWORD=adminispw
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db


volumes:
  npm_package:
  mongo_configdb:
  mongo_db:
