// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  large: string;
  textInput: string;
}
export const cssExports: CssExports;
export default cssExports;
