version: '3'

services:
  authserver:
    # build:
    #   context: docker
    #   dockerfile: Dockerfile
    image: node:14-alpine
    # ports:
    #   - 8888:8888
    environment:
      - NODE_ENV=
    working_dir: /opt/app
    command: >
      sh -c "yarn && yarn start \
         --port=8888 \
         --domain=app.localhost \
         --frontend=static \
         --admin-username=admin \
         --create-user-admin-password=root \
         --create-user-admin-crypto=pass \
         --storage=memory \
         --storage-dbname=authserver \
         --session-secret=auth_S_E_C_R_E_T_server \
         "
    restart: unless-stopped
    volumes:
      - npm_package:/opt/app/node_modules
      - ../../src:/opt/app/src
      - ../../package.json:/opt/app/package.json
      - ../../yarn.lock:/opt/app/yarn.lock
      - ../../webpack.config.js:/opt/app/webpack.config.js
      - ../../webpack.common.config.js:/opt/app/webpack.common.config.js
      - ../../tsconfig.webpack.json:/opt/app/tsconfig.webpack.json

  nginx:
    image: nginx
    ports:
      - 4000:80
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=5870b6c1a43b98
      - MONGO_INITDB_ROOT_PASSWORD=authserverpassw
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/html1:/usr/share/nginx/html1:ro
      - ./nginx/log:/var/log/nginx/:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

volumes:
  npm_package:
