version: '3'

services:
  authserver:
    # build:
    #   context: docker
    #   dockerfile: Dockerfile
    image: node:14-alpine
    ports:
      - 8888:8888
    depends_on:
      - mongo
    environment:
      - NODE_ENV=
    working_dir: /opt/app
    command: >
      sh -c "yarn && yarn start \
         --port=8888 \
         --domain=app.localhost \
         --frontend=static \
         --admin-username=admin \
         --create-user-admin-password=root \
         --create-user-admin-crypto=pass \
         --storage=mongo \
         --storage-dbname=authserver \
         --mongodb-domain=5870b6c1a43b98:authserverpassw@mongo:27017 \
         --session-secret=auth_S_E_C_R_E_T_server \
         "
    restart: unless-stopped
    volumes:
      - npm_package:/opt/app/node_modules
      - ../../src:/opt/app/src
      - ../../package.json:/opt/app/package.json
      - ../../yarn.lock:/opt/app/yarn.lock
      - ../../webpack.config.js:/opt/app/webpack.config.js
      - ../../webpack.common.config.js:/opt/app/webpack.common.config.js
      - ../../tsconfig.webpack.json:/opt/app/tsconfig.webpack.json

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=5870b6c1a43b98
      - MONGO_INITDB_ROOT_PASSWORD=authserverpassw
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

volumes:
  npm_package:
  mongo_configdb:
  mongo_db:
